### ISSUE TITLE
Tooltip Redesign

### ISSUE THREAD

**Issue by Rohithgilla12** [IceCereal/CoronaVisualizer#58]
Delhi
I : 1640 | D : 34
 ↑ 45          ↑ 23

the ↑45 should be a white and smaller font. The numbers for ↑() can be gotten from the last 24 hours API. The colours for I and D is the same as that at the top of the website.

Similar to this in district tooltips
<img width="71" alt="Screenshot 2020-04-30 at 2 46 52 PM" src="https://user-images.githubusercontent.com/19389850/80693964-72714a00-8af1-11ea-8861-18b220e8c154.png">

**Comment by ach4l** [comment]
I am going to try this tonight, see how far I can go

**Comment by ach4l** [comment]
https://stackoverflow.com/questions/484137/is-it-possible-to-format-an-html-tooltip-title-attribute

Top Answer:

No. But there are other options out there like Overlib, and jQuery that allow you this freedom.

jTip : http://www.codylindley.com/blogstuff/js/jtip/
jQuery Tooltip : https://jqueryui.com/tooltip/
Personally, I would suggest jQuery as the route to take. It's typically very unobtrusive, and requires no additional setup in the markup of your site (with the exception of adding the jquery script tag in your <head>).

**Comment by ach4l** [comment]
I didnt get anywhere. #LeMoiNoob
