### ISSUE TITLE
Table Revamp

### ISSUE THREAD

**Issue by Rohithgilla12** [IceCereal/CoronaVisualizer#60]
The current table consists of 4 rows in total, now we want to make in concise into two.

For example

<img width="1120" alt="Screenshot 2020-05-01 at 2 00 59 PM" src="https://user-images.githubusercontent.com/19389850/80793232-318e3980-8bb4-11ea-86ce-61fe4e2a3c9f.png">

has 4 rows, we want to have 2 rows with New cases just beside Total cases as a small text with arrow up icon
Similar to this.
<img width="109" alt="Screenshot 2020-05-01 at 2 02 14 PM" src="https://user-images.githubusercontent.com/19389850/80793295-5f737e00-8bb4-11ea-9dd9-9ab77aea0213.png">

Use #eada0a as font color for `cases` column and #958686 for `deaths` column.

**Comment by larizzatg** [comment]
Hi @Rohithgilla12 I'll like to work on this.

**Comment by Rohithgilla12** [comment]
Yeah sure awesome.
Assigning it to you!
Thanks.

**Comment by ach4l** [comment]
Hey, do you need any help in figuring out the code for the table? It might not be very intuitive.

**Comment by larizzatg** [comment]
> Hey, do you need any help in figuring out the code for the table? It might not be very intuitive.

Hello, thanks I could find the code, at first I had some trouble because I didn't know Jekyll but I set up a Jekyll image with docker and now I'm checking the datatable API (another new thing) :)

**Comment by larizzatg** [comment]
> Use #eada0a as font color for `cases` column and #958686 for `deaths` column.

Hi @Rohithgilla12 those colors will be for the small text or for the entire column. If is for the column should I use red for the small text.

**Comment by ach4l** [comment]
Hey, answering for @Rohithgilla12 , it will be for the small text.

**Comment by ach4l** [comment]
Thanka a lot @larizzatg . That was quick!

**Comment by larizzatg** [comment]
Always :)

**Comment by Rohithgilla12** [comment]
Thanks a lot for your contribution.
Closing the issue, #75 fixed it.
